apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: rapidbase
type: Opaque
stringData:
  POSTGRES_USER: "rapidbase"
  POSTGRES_PASSWORD: "rb_db_v9xK2mP7qL4wN1jR8tF5cH3bZ6"
  POSTGRES_DB: "rapidbase"
  DATABASE_URL: "postgresql://rapidbase:rb_db_v9xK2mP7qL4wN1jR8tF5cH3bZ6@postgres:5432/rapidbase"
