apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: rapidbase
type: Opaque
stringData:
  REDIS_PASSWORD: "rb_redis_v9xK2mP7qL4wN1jR8t"
  REDIS_URL: "redis://:rb_redis_v9xK2mP7qL4wN1jR8t@redis:6379"
