apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: rapidbase
type: Opaque
stringData:
  DATABASE_URL: "postgresql://rapidbase:rb_db_v9xK2mP7qL4wN1jR8tF5cH3bZ6@postgres:5432/rapidbase"
  REDIS_URL: "redis://:rb_redis_v9xK2mP7qL4wN1jR8t@redis:6379"
  JWT_SECRET: "rb_jwt_sec_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D0E1F2"
  JWT_REFRESH_SECRET: "rb_jwt_ref_Z1Y2X3W4V5U6T7S8R9Q0P1O2N3M4L5K6J7I8H9G0F1E2D3C4B5A6a7b8c9d0e1f2"
  COOKIE_SECRET: "rb_cookie_sec_q1w2e3r4t5y6u7i8o9p0a1s2d3f4g5h6j7k8l9z0x1c2v3b4n5m6"
  SMTP_USER: "ayushsoni6997@gmail.com"
  SMTP_PASS: "fulsuuikygownich"
