apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: rapidbase
  labels:
    app: database-service
spec:
  selector:
    app: database-service
  ports:
    - name: http
      port: 4003
      targetPort: 4003
      protocol: TCP
  type: ClusterIP
