apiVersion: v1
kind: ConfigMap
metadata:
  name: project-service-config
  namespace: rapidbase
data:
  NODE_ENV: "production"
  PORT: "4002"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "465"
  SMTP_FROM: "RapidBase <ayushsoni6997@gmail.com>"
  FRONTEND_URL: "http://localhost"
