apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: rapidbase
  labels:
    app: project-service
spec:
  selector:
    app: project-service
  ports:
    - name: http
      port: 4002
      targetPort: 4002
      protocol: TCP
  type: ClusterIP
