apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: rapidbase
  labels:
    app: postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest:v12.2.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: postgrest-config
            - secretRef:
                name: postgrest-secrets
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
