apiVersion: v1
kind: Secret
metadata:
  name: postgrest-secrets
  namespace: rapidbase
type: Opaque
stringData:
  PGRST_DB_URI: "postgresql://rapidbase:rb_db_v9xK2mP7qL4wN1jR8tF5cH3bZ6@postgres:5432/rapidbase"
