name: Mirror to GitLab

on:
  push:
    branches: [ "*" ] # Triggers on all branch pushes
  delete: # Triggers when a branch or tag is deleted

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Push to GitLab
        env:
          GITLAB_NAMESPACE: "rapidbase" # The group or username the repo belongs to
          GITLAB_REPO: "major1"         # The actual name of the repository
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/$GITLAB_NAMESPACE/$GITLAB_REPO.git
          git push gitlab --all --force
          git push gitlab --tags --force
